const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process');
const root=path.join(__dirname,'..'),renderer=require('../clergy-render');
test('shared preview renderer escapes text and exposes public fields only',()=>{const r=structuredClone(require('../_content/clergy.json').records[1]);r.displayName='A <script> & "person"';r.internalNotes='PRIVATE RESEARCH MARKER';r.sources=['PRIVATE SOURCE MARKER'];r.primaryImage.copyrightPermission='PRIVATE PERMISSION MARKER';const html=renderer.profile(r)+renderer.card(r);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/);assert.doesNotMatch(html,/PRIVATE/);assert.match(html,/From the archive/);});
test('archive build excludes drafts and internal notes, updates searchable public names and survives missing teaser portraits',()=>{const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'clergy-build-'));try{
  fs.mkdirSync(path.join(temporary,'_content'));
  for(const file of ['build-clergy-archive.js','clergy-render.js','build-search-index.js','publications-model.js','index.html','our-history.html'])fs.copyFileSync(path.join(root,file),path.join(temporary,file));
  const data=structuredClone(require('../_content/clergy.json'));data.records.reverse();const draft=structuredClone(data.records[0]);draft.id='fixture-only';draft.displayName='DRAFT PRIVATE MARKER';draft.biography=['DRAFT STORY MARKER'];draft.published=false;data.records.push(draft);data.records.push({id:'minimal-public-fixture',displayName:'Name Only Public Fixture',role:'',servicePeriods:[],primaryImage:null,archiveImages:[],biography:[],parishContext:[],didYouKnow:[],sources:[],internalNotes:'',published:true});data.records.forEach(r=>{r.internalNotes='PRIVATE RESEARCH MARKER';r.sources=['PRIVATE SOURCE MARKER'];});data.records=data.records.filter(r=>r.id!=='alfred-burmester');data.records.find(r=>r.id==='barbara-steadman-allen').primaryImage=null;data.records.find(r=>r.id==='arthur-bedford').primaryImage.src='assets/images/clergy/2-960.jpg';data.records.find(r=>r.id==='arthur-bedford').primaryImage.thumbnail='assets/images/clergy/2-360.jpg';data.records.find(r=>r.id==='aw-douglas').displayName='Researched Fixture Name';
  fs.writeFileSync(path.join(temporary,'_content/clergy.json'),JSON.stringify(data));execFileSync(process.execPath,[path.join(temporary,'build-clergy-archive.js')]);execFileSync(process.execPath,[path.join(temporary,'build-search-index.js')]);
  const html=fs.readFileSync(path.join(temporary,'those-who-have-served.html'),'utf8'),index=fs.readFileSync(path.join(temporary,'index.html'),'utf8'),search=fs.readFileSync(path.join(temporary,'search-index.json'),'utf8'),projection=fs.readFileSync(path.join(temporary,'clergy-data.json'),'utf8');
  for(const content of [html,index,search,projection])assert.doesNotMatch(content,/DRAFT PRIVATE|DRAFT STORY|PRIVATE RESEARCH|PRIVATE SOURCE/);
  const archiveSearch=JSON.parse(search).find(p=>p.url==='those-who-have-served.html');assert.doesNotMatch(archiveSearch.content,/Alfred Burmester/);assert.doesNotMatch(index,/Alfred Burmester/);assert.match(search,/Name Only Public Fixture/);assert.match(html,/Name Only Public Fixture/);assert.match(search,/Researched Fixture Name/);assert.doesNotMatch(html,/id="alfred-burmester"/);assert.match(index,/assets\/images\/clergy\/2-360.jpg/);
  assert.ok(html.indexOf('href="#thomas-roger-ffowke"')<html.indexOf('href="#gerrard-andrewes"'));
  assert.deepEqual(JSON.parse(projection).map(r=>r.id).sort(),data.records.filter(r=>r.published).map(r=>r.id).sort());
  const hero=s=>s.match(/<section[^>]+class="[^"]*home-hero[\s\S]*?<\/section>/)?.[0];assert.equal(hero(index),hero(fs.readFileSync(path.join(root,'index.html'),'utf8')));
}finally{fs.rmSync(temporary,{recursive:true,force:true});}});

test('renderer uses conservative escaped name/caption alt fallbacks and honours manual alt',()=>{const r=structuredClone(require('../_content/clergy.json').records.find(r=>r.primaryImage));r.displayName='Known & Name';r.primaryImage.alt='';r.primaryImage.caption='Archive caption';r.archiveImages=[structuredClone(r.primaryImage)];assert.match(renderer.card(r),/alt="Historical photograph associated with Known &amp; Name: Archive caption"/);assert.match(renderer.profile(r),/alt="Historical photograph associated with Known &amp; Name: Archive caption"/);r.primaryImage.alt='Manual description';assert.match(renderer.card(r),/alt="Manual description"/);assert.equal(renderer.dates({...r,servicePeriods:[]}), 'Service dates unknown');assert.equal(renderer.dates({...r,servicePeriods:[{start:null,end:1910}]}),'Display ends 1910');});
