const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {buildCalendar}=require('./azure-function/src/calendar-model');const root=__dirname,source=fs.readFileSync(path.join(root,'_content/calendar-source.ics'),'utf8');
const series={id:'fixture-search',title:'UpcomingRecurrenceFixture',start:'2027-01-01T10:00',end:'2027-01-01T11:00',timeZone:'Europe/London',location:'Fixture venue',status:'published',recurrence:{frequency:'monthly',interval:1,ordinal:1,weekday:2,end:{type:'date',until:'2027-05-31'}}};
const fixedBuild=(source,data)=>buildCalendar(source,data,{range:{from:'2027-01-01',to:'2027-12-31'}});
const editorial=exceptions=>({hiddenEventIds:[],overrides:[],events:[],series:[series],exceptions});
const exception={seriesId:series.id,occurrenceStart:'2027-02-02T10:00',cancelled:true};
function index(data){let output;const fake={...fs,existsSync:p=>p.endsWith('events.json'),readFileSync:p=>p.endsWith('events.json')?JSON.stringify(data):'<html><title>Calendar</title><main>Church Calendar</main></html>',writeFileSync:(_p,v)=>output=v,readdirSync:()=>[{name:'calendar.html',isDirectory:()=>false,isFile:()=>true}]};vm.runInNewContext(fs.readFileSync(path.join(root,'build-search-index.js'),'utf8'),{require:n=>n==='node:fs'?fake:n.startsWith('./')?require(path.join(root,n)):require(n),__dirname:root,console:{log(){}}});return output;}
test('bounded recurring occurrences enter public search while cancelled and draft occurrences stay absent',()=>{const data=fixedBuild(source,editorial([exception]));const out=index(data);assert.match(out,/UpcomingRecurrenceFixture/);assert.match(out,/2027-01-05T10:00/);assert.doesNotMatch(out,/2027-02-02T10:00/);assert.equal(data.items.filter(e=>e.seriesId).length,4);const draft=fixedBuild(source,{...editorial([]),series:[{...series,status:'draft'}]});assert.doesNotMatch(index(draft),/UpcomingRecurrenceFixture/)});
test('series edits and exceptions change the existing version payload hash; no new refresh mechanism required',()=>{const hash=d=>crypto.createHash('sha256').update(JSON.stringify(d)).digest('hex');const a=fixedBuild(source,editorial([]));const b=fixedBuild(source,editorial([exception]));assert.notEqual(hash(a),hash(b));assert.equal(hash(b),hash(fixedBuild(source,editorial([exception]))));const c=fixedBuild(source,{...editorial([]),series:[{...series,title:'Changed title'}]});assert.notEqual(hash(a),hash(c))});
