(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.churchClergyRender=factory();})(globalThis,()=>{
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dates = record => record.servicePeriods.map(period => period.start ? (period.end ? `${period.start}–${period.end}` : `Display begins ${period.start}`) : (period.end ? `Display ends ${period.end}` : '')).filter(Boolean).join(' · ') || 'Service dates unknown';
const firstYear = record => Math.min(...record.servicePeriods.map(p=>p.start ?? Infinity));
const altText = (image,record) => image.alt?.trim() ? image.alt : `Historical photograph associated with ${record.displayName}${image.caption?.trim()?`: ${image.caption.trim()}`:''}`;
const photo = (image, small = false, record) => `<img src="${esc(small ? image.thumbnail : image.src)}" alt="${esc(record?altText(image,record):image.alt)}" loading="lazy" decoding="async">`;
const safeSourceURL = value => { if(typeof value!=='string')return ''; const url=value.trim();try {const parsed=new URL(url);return /^https?:\/\//i.test(url)&&['http:','https:'].includes(parsed.protocol)&&!parsed.username&&!parsed.password&&!/[\s\\]/.test(url)?url:'';}catch{return '';}};
const sourceList = record => {const sources=(record.sources||[]).filter(s=>s&&typeof s==='object'&&s.public===true&&typeof s.title==='string'&&s.title.trim());return sources.length?`<section class="clergy-sources"><h3>Sources &amp; further reading</h3><ul>${sources.map(s=>`<li><strong>${esc(s.title)}</strong>${s.notes?`<p>${esc(s.notes)}</p>`:''}${safeSourceURL(s.url)?`<a class="text-link" href="${esc(safeSourceURL(s.url))}" target="_blank" rel="noopener noreferrer" aria-label="View source: ${esc(s.title)} (opens in a new tab)">View source <span aria-hidden="true">→</span></a>`:''}</li>`).join('')}</ul></section>`:'';};
const card = record => `<li><a class="clergy-card" href="#${esc(record.id)}">${record.primaryImage ? photo(record.primaryImage, true,record) : '<div class="clergy-no-portrait">From the parish record</div>'}<div><p class="eyebrow">${esc(dates(record))}</p><h2>${esc(record.displayName)}</h2><span class="text-link">Discover their story <span aria-hidden="true">→</span></span></div></a></li>`;
const profile = record => `<details class="clergy-profile" id="${esc(record.id)}"><summary>${esc(record.displayName)} · ${esc(dates(record))}</summary><div class="clergy-profile-content"><div>${record.primaryImage ? `<figure>${photo(record.primaryImage,false,record)}<figcaption>${esc(record.primaryImage.caption)}</figcaption></figure>` : ''}</div><div><p class="eyebrow">${esc(record.role)} · ${esc(dates(record))}</p><h2>${esc(record.displayName)}</h2>${[['Their story',record.biography],['St Michael’s in their time',record.parishContext],['Did you know?',record.didYouKnow]].filter(([,paragraphs]) => paragraphs.length).map(([title,paragraphs]) => `<section><h3>${title}</h3>${paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('')}${!record.biography.length ? `<p>The parish working record lists ${esc(record.displayName)} as ${record.role==='Rector'?'Rector of Mickleham':record.role?esc(record.role)+' at St Michael’s':'associated with St Michael’s'}, ${esc(dates(record))}.</p>` : ''}${sourceList(record)}${record.archiveImages.length ? `<section><h3>From the archive</h3><div class="clergy-thumbnails">${record.archiveImages.map((image,i)=>`<a href="${esc(image.src)}" data-archive-image="${i}">${photo(image,true,record)}<span>View archive photograph ${i+1}</span></a>`).join('')}</div></section>` : ''}</div></div></details>`;
return Object.freeze({esc,dates,firstYear,altText,photo,card,profile,safeSourceURL,sourceList});
});
