const test=require('node:test'),assert=require('node:assert/strict'),sharp=require('sharp');
const {createClergyHandler}=require('../src/clergy-publishing');
const model=require('../src/clergy-model');
const archive=require('../../_content/clergy.json');
const SHA='a'.repeat(40),HEAD='b'.repeat(40),NEXT='c'.repeat(40),COMMIT='d'.repeat(40);
const principal={auth_typ:'aad',claims:Object.entries({tid:'9188040d-6c67-4c5b-b112-36a304b66dad',oid:'00000000-0000-0000-f978-44e4d44cc925',sub:'AAAAAAAAAAAAAAAAAAAAACmKQtkQPpxJMB93l8aduYc',iss:'https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0'}).map(([typ,val])=>({typ,val}))};
const payload=()=>({sha:SHA,headSha:HEAD,archive:structuredClone(archive),uploads:[]});
function request(method,body,identity=principal,options={}){const headers=new Headers({'Content-Type':'application/json',...options.headers});if(identity)headers.set('x-ms-client-principal',typeof identity==='string'?identity:Buffer.from(JSON.stringify(identity)).toString('base64'));return {method,headers,query:new URLSearchParams(options.query||''),body:new Blob([typeof body==='string'?body:JSON.stringify(body)]).stream()};}
function fixture(options={}){const operations=[],permissions=[];const call=(name,fn)=>async params=>{operations.push({name,params});return fn(params);};const client={rest:{repos:{getContent:call('read',p=>({data:{type:'file',path:p.path,encoding:'base64',sha:SHA,content:Buffer.from(JSON.stringify(options.current||archive)).toString('base64')}}))},git:{getRef:call('ref',()=>({data:{object:{sha:HEAD}}})),getCommit:call('parent',()=>({data:{tree:{sha:SHA}}})),createBlob:call('blob',()=>({data:{sha:NEXT}})),createTree:call('tree',()=>({data:{sha:NEXT}})),createCommit:call('commit',()=>({data:{sha:COMMIT}})),updateRef:call('advance',()=>{if(options.race)throw Object.assign(new Error('secret SDK detail'),{status:422});if(options.fail)throw new Error('secret SDK detail');return {data:{}};})}}};return {operations,permissions,handler:createClergyHandler({readConfiguration:()=>({}),createClient:async(_,permission)=>{permissions.push(permission);return client;}})};}
test('archive GET reads fixed metadata at an immutable Dev snapshot, no public cache',async()=>{const f=fixture(),r=await f.handler(request('GET',{}));assert.equal(r.status,200);assert.deepEqual(r.jsonBody.archive,archive);assert.equal(r.jsonBody.sha,SHA);assert.equal(r.jsonBody.headSha,HEAD);assert.equal(r.headers['Cache-Control'],'no-store');assert.deepEqual(f.permissions,['read']);assert.equal(f.operations[1].params.ref,HEAD);assert.equal(f.operations[1].params.path,'_content/clergy.json');});
test('archive authentication and every immutable allowlist binding required before repository access',async()=>{for(const method of ['GET','PUT'])for(const identity of [null,'broken',...['tid','oid','sub','iss'].map(typ=>{const p=structuredClone(principal);p.claims.find(c=>c.typ===typ).val+='x';return p;})]){const f=fixture(),r=await f.handler(request(method,payload(),identity,{headers:{'x-admin-authorized':'true'}}));assert.ok([401,403].includes(r.status));assert.equal(f.operations.length,0);}});
test('archive rejects arbitrary branch, repository, path, credentials and all query parameters',async()=>{for(const key of ['branch','path','owner','repo','token','administrator']){const f=fixture();assert.equal((await f.handler(request('PUT',{...payload(),[key]:'main'}))).status,400);assert.equal(f.operations.length,0);}for(const method of ['GET','PUT']){const f=fixture();assert.equal((await f.handler(request(method,payload(),principal,{query:'branch=main'}))).status,400);assert.equal(f.operations.length,0);}});
test('archive publishes only fixed metadata with base tree and non-forced Dev parent protection',async()=>{const f=fixture(),p=payload();p.archive.records[0].internalNotes='Research fixture only';const r=await f.handler(request('PUT',p));assert.equal(r.status,200);assert.deepEqual(f.permissions,['read','write']);assert.deepEqual(f.operations.find(o=>o.name==='tree').params.tree.map(t=>t.path),['_content/clergy.json']);assert.equal(f.operations.find(o=>o.name==='tree').params.base_tree,SHA);assert.deepEqual(f.operations.find(o=>o.name==='commit').params.parents,[HEAD]);assert.deepEqual(f.operations.find(o=>o.name==='advance').params,{owner:'micklehamchurch',repo:'website',ref:'heads/Dev',sha:COMMIT,force:false});assert.match(r.jsonBody.archive.updatedAt,/Z$/);for(const op of f.operations){assert.equal(op.params.owner,'micklehamchurch');assert.equal(op.params.repo,'website');}});
test('stale blob or unrelated Dev advance stops writes; competing commit is a safe conflict',async()=>{for(const key of ['sha','headSha']){const f=fixture(),p=payload();p[key]=NEXT;assert.equal((await f.handler(request('PUT',p))).status,409);assert.deepEqual(f.permissions,['read']);assert.ok(!f.operations.some(o=>o.name==='blob'));}const f=fixture({race:true}),r=await f.handler(request('PUT',payload()));assert.equal(r.status,409);assert.equal(r.jsonBody.error,'archive-version-conflict');assert.doesNotMatch(JSON.stringify(r),/secret/);});
test('repository errors never expose secrets or SDK messages',async()=>{const f=fixture({fail:true}),r=await f.handler(request('PUT',payload()));assert.equal(r.status,502);assert.doesNotMatch(JSON.stringify(r),/secret/);});
test('add draft without portrait or biography, multiple periods, publish and unpublish preserve originals',async()=>{const p=payload();const draft={...structuredClone(p.archive.records[0]),id:'fixture-draft',displayName:'Fixture only',servicePeriods:[{start:1900,end:1905},{start:1910,end:null}],published:false};p.archive.records.push(draft);p.archive.records[1].published=false;let r=await fixture().handler(request('PUT',p));assert.equal(r.status,200);assert.equal(r.jsonBody.archive.records.at(-1).primaryImage,null);assert.deepEqual(r.jsonBody.archive.records.at(-1).servicePeriods,draft.servicePeriods);assert.equal(r.jsonBody.archive.records[1].published,false);draft.published=true;r=await fixture().handler(request('PUT',p));assert.equal(r.status,200);assert.equal(r.jsonBody.archive.records.at(-1).published,true);});
test('gallery reorder, removal and selecting primary preserve biography and historical metadata',async()=>{const p=payload(),r=p.archive.records.find(r=>r.id==='john-harkin'),old=structuredClone(r);r.archiveImages.reverse();r.primaryImage=structuredClone(r.archiveImages[0]);r.archiveImages.pop();const result=await fixture().handler(request('PUT',p));assert.equal(result.status,200);const updated=result.jsonBody.archive.records.find(r=>r.id==='john-harkin');assert.deepEqual(updated.biography,old.biography);assert.deepEqual(updated.servicePeriods,old.servicePeriods);assert.equal(updated.archiveImages.length,old.archiveImages.length-1);assert.equal(updated.primaryImage.src,old.archiveImages.at(-1).src);});
test('cannot delete records, edit unassigned research sources, pair unrelated paths or traverse directories',async()=>{for(const mutate of [p=>p.archive.records.pop(),p=>p.archive.unassignedSources=[],p=>p.archive.records[1].primaryImage.src='../../index.html',p=>p.archive.records[1].primaryImage.src='assets/images/clergy/nonexistent.jpg',p=>p.archive.records[1].primaryImage.thumbnail=p.archive.records[2].primaryImage.thumbnail,p=>p.archive.records[1].primaryImage.originalFilename='changed.jpeg']){const p=payload();mutate(p);const f=fixture();assert.equal((await f.handler(request('PUT',p))).status,400);assert.ok(!f.operations.some(o=>o.name==='blob'));}});
test('strict fields, script content, duplicate IDs and invalid service periods are rejected',async()=>{for(const mutate of [p=>p.archive.records[0].email='private',p=>p.archive.records[0].displayName='<script>',p=>p.archive.records[0].servicePeriods=[{start:1900,end:1800}],p=>p.archive.records[0].servicePeriods=[{start:'1900',end:null}],p=>p.archive.records[1].id=p.archive.records[0].id,p=>p.archive.records[0].biography=['x'.repeat(10001)]]){const p=payload();mutate(p);assert.equal((await fixture().handler(request('PUT',p))).status,400);}});
const uploadId='11111111-1111-4111-8111-111111111111';
async function imageUpload(format='jpeg'){const bytes=await sharp({create:{width:12,height:16,channels:3,background:'#345678'}}).toFormat(format).toBuffer();return {id:uploadId,fileName:`fixture.${format==='jpeg'?'jpg':format}`,mimeType:`image/${format}`,base64:bytes.toString('base64')};}
function attachUpload(p,u){p.uploads=[u];p.archive.records[0].primaryImage={src:`upload:${u.id}`,thumbnail:`upload:${u.id}`,alt:'Test fixture portrait',caption:'Fixture only',date:null,source:'',credit:null,copyrightPermission:null,originalFilename:u.fileName,derivativeCreated:true};}
test('safe JPEG PNG WebP upload preserves original bytes and creates only scoped optimized versions',async()=>{for(const format of ['jpeg','png','webp']){const p=payload(),u=await imageUpload(format);attachUpload(p,u);const f=fixture(),r=await f.handler(request('PUT',p));assert.equal(r.status,200);const paths=f.operations.find(o=>o.name==='tree').params.tree.map(t=>t.path);assert.equal(paths.length,4);assert.match(paths[0],/^_archive-sources\/clergy\/uploads\/[a-f0-9-]{36}\.(jpg|png|webp)$/);assert.match(paths[1],/^assets\/images\/clergy\/uploads\/[a-f0-9-]{36}-1600.jpg$/);assert.match(paths[2],/-360.jpg$/);assert.equal(f.operations.filter(o=>o.name==='blob')[0].params.content,u.base64);for(const blob of f.operations.filter(o=>o.name==='blob').slice(1,3)){const m=await sharp(Buffer.from(blob.params.content,'base64')).metadata();assert.equal(m.format,'jpeg');assert.equal(m.exif,undefined);}assert.equal(r.jsonBody.archive.records[0].primaryImage.src,paths[1]);assert.equal(r.jsonBody.archive.records[0].primaryImage.originalFilename,u.fileName);}});
test('replacement image leaves biographies and gallery intact',async()=>{const p=payload(),u=await imageUpload();const old=structuredClone(p.archive.records[1]);p.uploads=[u];p.archive.records[1].primaryImage={...old.primaryImage,src:`upload:${u.id}`,thumbnail:`upload:${u.id}`};const r=await fixture().handler(request('PUT',p));assert.equal(r.status,200);assert.deepEqual(r.jsonBody.archive.records[1].biography,old.biography);assert.deepEqual(r.jsonBody.archive.records[1].archiveImages,old.archiveImages);});
test('adding a gallery upload supports blank unknown metadata',async()=>{const p=payload(),u=await imageUpload();attachUpload(p,u);p.archive.records[0].archiveImages.push(p.archive.records[0].primaryImage);p.archive.records[0].primaryImage=null;const r=await fixture().handler(request('PUT',p));assert.equal(r.status,200);assert.equal(r.jsonBody.archive.records[0].archiveImages[0].date,null);assert.equal(r.jsonBody.archive.records[0].archiveImages[0].source,'');});
test('renamed executable HTML SVG, corrupt images, mime mismatch and animated images cannot be uploaded',async()=>{const valid=await imageUpload();for(const u of [{...valid,base64:Buffer.from('<svg onload="alert(1)">').toString('base64')},{...valid,base64:Buffer.from('MZ executable').toString('base64')},{...valid,mimeType:'image/png'},{...valid,fileName:'fixture.svg'},{...valid,fileName:'../fixture.jpg'},{...valid,base64:'!!!!'},{...valid,base64:Buffer.from([255,216,255,0,1,2]).toString('base64')}]){const p=payload();attachUpload(p,u);const f=fixture();assert.equal((await f.handler(request('PUT',p))).status,400);assert.ok(!f.operations.some(o=>o.name==='blob'));}});
test('oversized images, batches and request streams are bounded, including absent Content-Length',async()=>{const valid=await imageUpload();const p=payload();attachUpload(p,{...valid,base64:Buffer.alloc(model.MAX_IMAGE+1).toString('base64')});assert.equal((await fixture().handler(request('PUT',p))).status,413);const many=payload();many.uploads=Array(7).fill(valid);assert.equal((await fixture().handler(request('PUT',many))).status,400);const r=request('PUT',payload(),principal,{headers:{'Content-Length':String(model.MAX_BODY+1)}});assert.equal((await fixture().handler(r)).status,413);const stream=request('PUT',' '.repeat(model.MAX_BODY+1));assert.equal((await fixture().handler(stream)).status,413);});
test('unknown or unreferenced uploads cannot write stray assets',async()=>{const p=payload();p.uploads=[await imageUpload()];const f=fixture();assert.equal((await f.handler(request('PUT',p))).status,400);assert.ok(!f.operations.some(o=>o.name==='blob'));const unknown=payload();attachUpload(unknown,await imageUpload());unknown.uploads=[];assert.equal((await fixture().handler(request('PUT',unknown))).status,400);});
test('large decoded dimensions and animated webp are rejected before writing',async()=>{
  const huge=await sharp({create:{width:8000,height:6000,channels:3,background:'#345678'}}).png().toBuffer();
  const frames=Buffer.concat([Buffer.alloc(12*16*3,100),Buffer.alloc(12*16*3,200)]);
  const animated=await sharp(frames,{raw:{width:12,height:32,channels:3,pageHeight:16}}).webp({loop:0}).toBuffer();
  assert.equal((await sharp(animated,{animated:true}).metadata()).pages,2);
  for(const [bytes,format] of [[huge,'png'],[animated,'webp']]){const p=payload();attachUpload(p,{id:uploadId,fileName:`fixture.${format}`,mimeType:`image/${format}`,base64:bytes.toString('base64')});const f=fixture();assert.equal((await f.handler(request('PUT',p))).status,400);assert.ok(!f.operations.some(o=>o.name==='blob'));}
});
test('public photographs without manual alt text publish without changing saved metadata',async()=>{const p=payload();p.archive.records[1].primaryImage.alt='';const result=await fixture().handler(request('PUT',p));assert.equal(result.status,200);assert.equal(result.jsonBody.archive.records[1].primaryImage.alt,'');p.archive.records[1].published=false;assert.equal((await fixture().handler(request('PUT',p))).status,200);});

test('authorised name-only publication defaults optional structure and remains searchable/renderable',async()=>{const p=payload();p.archive.records.push({id:'minimal-fixture',displayName:'Minimal Fixture',published:true});const result=await fixture().handler(request('PUT',p));assert.equal(result.status,200);const r=result.jsonBody.archive.records.at(-1);assert.equal(r.role,'');assert.deepEqual(r.servicePeriods,[]);assert.deepEqual(r.biography,[]);assert.equal(r.internalNotes,'');assert.equal(r.primaryImage,null);});
test('incomplete service dates including unknown starts and ends can publish',async()=>{for(const servicePeriods of [[],[{start:null,end:null}],[{start:null,end:1910}],[{start:1900,end:null}],[{end:1910}]]){const p=payload();p.archive.records[0].servicePeriods=servicePeriods;assert.equal((await fixture().handler(request('PUT',p))).status,200);}});
test('current Mowsurth profile can publish as entered without rewriting any metadata',async()=>{const p=payload(),person=p.archive.records.find(r=>r.displayName==='W m.Mowsurth'),before=structuredClone(person);assert(person);person.published=true;const result=await fixture().handler(request('PUT',p));assert.equal(result.status,200);assert.deepEqual(result.jsonBody.archive.records.find(r=>r.id===person.id),{...before,published:true});});
test('additional photographs without manual alt text publish with empty optional metadata',async()=>{const p=payload();p.archive.records.find(r=>r.id==='john-harkin').archiveImages.forEach(i=>i.alt='');assert.equal((await fixture().handler(request('PUT',p))).status,200);});
test('validation failures expose specific safe categories without input or SDK details',async()=>{for(const [mutate,error] of [[p=>p.archive.records[0].displayName='','archive-name-required'],[p=>p.archive.records[0].servicePeriods=[{start:1900,end:1800}],'archive-invalid-years'],[p=>p.archive.records[1].primaryImage.src='../private','archive-unsafe-image'],[p=>p.archive.records[0].displayName='<script>','archive-unsafe-text']]){const p=payload();mutate(p);const r=await fixture().handler(request('PUT',p));assert.equal(r.status,400);assert.equal(r.jsonBody.error,error);}});

test('explicit Published and Draft record removal persists only fixed metadata and leaves others unchanged',async()=>{for(const id of ['thomas-roger-ffowke',archive.records.find(r=>!r.published).id]){const p=payload();p.removedRecordIds=[id];p.archive.records=p.archive.records.filter(r=>r.id!==id);const f=fixture(),result=await f.handler(request('PUT',p));assert.equal(result.status,200);assert(!result.jsonBody.archive.records.some(r=>r.id===id));assert.deepEqual(result.jsonBody.archive.records,archive.records.filter(r=>r.id!==id));assert.deepEqual(f.operations.find(o=>o.name==='tree').params.tree.map(t=>t.path),['_content/clergy.json']);assert.equal(f.operations.find(o=>o.name==='advance').params.ref,'heads/Dev');assert.equal(f.operations.find(o=>o.name==='advance').params.force,false);}});
test('shared and dedicated image assets are never deleted by record removal',async()=>{const current=structuredClone(archive);current.records[0].primaryImage=structuredClone(current.records[1].primaryImage);const p={...payload(),archive:structuredClone(current),removedRecordIds:[current.records[1].id]};p.archive.records.splice(1,1);const f=fixture({current}),result=await f.handler(request('PUT',p));assert.equal(result.status,200);assert.deepEqual(result.jsonBody.archive.records[0].primaryImage,current.records[0].primaryImage);assert.deepEqual(f.operations.find(o=>o.name==='tree').params.tree.map(t=>t.path),['_content/clergy.json']);assert(!f.operations.some(o=>o.name==='delete'));});
test('record deletion requires exact explicit IDs; paths, unknown IDs, duplicates and contradictory IDs fail',async()=>{for(const ids of [undefined,[],['../../index.html'],['unknown'],['thomas-roger-ffowke','thomas-roger-ffowke'],null]){const p=payload();p.archive.records=p.archive.records.filter(r=>r.id!=='thomas-roger-ffowke');p.removedRecordIds=ids;const f=fixture(),result=await f.handler(request('PUT',p));assert.equal(result.status,400);assert(!f.operations.some(o=>o.name==='blob'));}const p=payload();p.removedRecordIds=['thomas-roger-ffowke'];assert.equal((await fixture().handler(request('PUT',p))).status,400);});
test('unauthorised and stale deletion requests cannot write; arbitrary branch/path selectors stay rejected',async()=>{const p=payload();p.removedRecordIds=['thomas-roger-ffowke'];p.archive.records.shift();for(const identity of [null,'broken']){const f=fixture(),result=await f.handler(request('PUT',p,identity));assert.ok([401,403].includes(result.status));assert.equal(f.operations.length,0);}for(const key of ['sha','headSha']){const stale={...p,[key]:NEXT},f=fixture();assert.equal((await f.handler(request('PUT',stale))).status,409);assert(!f.operations.some(o=>o.name==='blob'));}for(const key of ['branch','path']){const f=fixture();assert.equal((await f.handler(request('PUT',{...p,[key]:'main'}))).status,400);assert.equal(f.operations.length,0);}});
