const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {createContactsHandler,MAX_BODY_BYTES}=require('../src/contacts');const {validateContacts}=require('../src/contacts-model');
const real=JSON.parse(fs.readFileSync(path.join(__dirname,'../../_content/contacts.json'),'utf8'));
const directory=()=>({sections:structuredClone(real.sections),contacts:[{id:'fixture-contact',section:real.sections[0].id,role:'Fixture role',name:'Fixture Person',phone:'',email:'',status:'published'}],pccMembers:[{id:'pcc-fixture',name:'PCC fixture',status:'draft'}]});
const identity = { auth_typ: 'aad', claims: Object.entries({ tid: '9188040d-6c67-4c5b-b112-36a304b66dad', oid: '00000000-0000-0000-f978-44e4d44cc925', sub: 'AAAAAAAAAAAAAAAAAAAAACmKQtkQPpxJMB93l8aduYc', iss: 'https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0' }).map(([typ, val]) => ({ typ, val })) };
const SHA = 'a'.repeat(40), NEXT_SHA = 'c'.repeat(40), COMMIT = 'd'.repeat(40);
function request(method = 'PUT', contacts = directory(), options = {}) {
  const principal = options.principal === undefined ? identity : options.principal;
  const headers = new Headers({ 'Content-Type': 'application/json', ...(options.headers || {}) });
  if (principal) headers.set('x-ms-client-principal', typeof principal === 'string' ? principal : Buffer.from(JSON.stringify(principal)).toString('base64'));
  const payload = options.body === undefined ? { sha: SHA, contacts, ...options.extra } : options.body;
  const text = typeof payload === 'string' ? payload : JSON.stringify(payload);
  return { method, headers, query: new URLSearchParams(options.query || ''), body: new Blob([text]).stream() };
}

function fixture(options={}){const reads=[],writes=[],permissions=[];const handler=createContactsHandler({readConfiguration:()=>({}),createClient:async(_c,p)=>{permissions.push(p);return{rest:{repos:{getContent:async params=>{reads.push(params);return{data:{type:'file',path:params.path,sha:SHA,encoding:'base64',content:Buffer.from(JSON.stringify(options.current||directory())).toString('base64')}}},createOrUpdateFileContents:async params=>{writes.push(params);if(options.race)throw{status:409};return{data:{content:{sha:NEXT_SHA},commit:{sha:COMMIT}}}}}}}}});return{handler,reads,writes,permissions}}
test('Contacts GET includes authenticated drafts and preserves every genuine current record',async()=>{const f=fixture({current:real});const r=await f.handler(request('GET'));assert.equal(r.status,200);assert.deepEqual(r.jsonBody.contacts,real);assert.equal(r.jsonBody.sha,SHA);assert.deepEqual(f.reads,[{owner:'micklehamchurch',repo:'website',ref:'Dev',path:'_content/contacts.json'}]);assert.equal(f.writes.length,0);assert.deepEqual(validateContacts(real),real)});
test('Contacts gates missing/malformed/non-admin and browser-supplied identity before any repository access',async()=>{for(const principal of [null,'bad', {...identity,claims:identity.claims.map(c=>c.typ==='sub'?{...c,val:'wrong'}:c)}])for(const method of ['GET','PUT']){const f=fixture();const r=await f.handler(request(method,directory(),{principal,headers:{'x-ms-client-principal-id':'spoof','x-admin-email':'edward.popov@outlook.com'}}));assert.equal(r.status,principal&&principal!=='bad'?403:401);assert.equal(f.reads.length,0);assert.equal(f.writes.length,0)}});
test('Contacts accepts edits/adds/PCC/draft/restoration/deletion/category/order only on the fixed Dev file',async()=>{const d=directory();d.contacts[0].name='Updated fixture';d.contacts[0].section=real.sections[1].id;d.contacts.push({...d.contacts[0],id:'added',status:'draft'});d.pccMembers=[{id:'added-pcc',name:'Added PCC',status:'published'},...d.pccMembers];const f=fixture();const r=await f.handler(request('PUT',d));assert.equal(r.status,200);assert.equal(f.writes.length,1);const w=f.writes[0];assert.equal(w.owner,'micklehamchurch');assert.equal(w.repo,'website');assert.equal(w.branch,'Dev');assert.equal(w.path,'_content/contacts.json');assert.equal(w.sha,SHA);assert.deepEqual(JSON.parse(Buffer.from(w.content,'base64')),d);assert.equal(r.jsonBody.sha,NEXT_SHA);
 const restored=structuredClone(d);restored.contacts[1].status='published';restored.contacts.shift();restored.pccMembers.reverse();const second=fixture({current:d});assert.equal((await second.handler(request('PUT',restored))).status,200);
});
test('Contacts rejects browser target selectors, extra schema keys and altered section metadata',async()=>{for(const extra of [{branch:'main'},{path:'x'},{owner:'other'},{repository:'other'},{filename:'x'},{administrator:true}]){const f=fixture();assert.equal((await f.handler(request('PUT',directory(),{extra}))).status,400);assert.equal(f.writes.length,0)}const f=fixture();assert.equal((await f.handler(request('PUT',directory(),{query:'branch=main'}))).status,400);const d=directory();d.sections[0].title='Changed';assert.equal((await f.handler(request('PUT',d))).status,400)});
test('Contacts stale SHA or GitHub race returns 409, no-op never requests write permission',async()=>{const f=fixture();assert.equal((await f.handler(request('PUT',directory(),{extra:{sha:'e'.repeat(40)}}))).status,409);assert.equal(f.writes.length,0);const d=directory();d.contacts[0].name='Changed';assert.equal((await fixture({race:true}).handler(request('PUT',d))).status,409);const same=fixture();assert.equal((await same.handler(request('PUT'))).jsonBody.unchanged,true);assert.deepEqual(same.permissions,['read'])});
test('Contacts validates IDs, optional empties, lengths, email, phone, category, status, HTML and unsupported ordering',async()=>{for(const change of [{id:'../bad'},{name:''},{name:'x'.repeat(181)},{role:'x'.repeat(181)},{email:'bad'},{phone:'123'},{phone:'1'.repeat(61)},{section:'unknown'},{section:'pcc-members'},{status:'hidden'},{name:'<script>'},{name:'bad\u0000'},{order:1},{groupId:''},{photo:'../x.jpg'},{photo:'https://example.org/x.jpg'}]){const d=directory();Object.assign(d.contacts[0],change);assert.throws(()=>validateContacts(d));const f=fixture();assert.equal((await f.handler(request('PUT',d))).status,400);assert.equal(f.writes.length,0)}for(const d of [null,[],{}, {...directory(),extra:true}, {...directory(),contacts:[null]}])assert.throws(()=>validateContacts(d));const duplicate=directory();duplicate.pccMembers[0].id=duplicate.contacts[0].id;assert.throws(()=>validateContacts(duplicate));const optional=directory();optional.contacts[0].photo='assets/images/contacts/fixture.webp';assert.equal(validateContacts(optional),optional)});
test('Contacts rejects malformed or excessive bounded bodies without repository access',async()=>{for(const [options,status]of [[{body:'{'},400],[{body:'x'.repeat(MAX_BODY_BYTES+1)},413],[{headers:{'content-length':String(MAX_BODY_BYTES+1)}},413],[{headers:{'content-type':'text/plain'}},400]]){const f=fixture();assert.equal((await f.handler(request('PUT',directory(),options))).status,status);assert.equal(f.reads.length,0)}});
test('Azure HttpRequest body streams follow the same authorized Contacts path',async()=>{const {HttpRequest}=require('@azure/functions');const d=directory();d.contacts[0].name='Azure fixture';const r=request('PUT',d);const httpRequest=new HttpRequest({method:'PUT',url:'https://example.org/api/contacts',headers:Object.fromEntries(r.headers),body:{string:JSON.stringify({sha:SHA,contacts:d})}});const f=fixture();assert.equal((await f.handler(httpRequest)).status,200);assert.equal(f.writes.length,1)});
