const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {createHomepageVersesHandler,MAX_BODY_BYTES}=require('../src/homepage-verses');const {validateHomepageVerses}=require('../src/homepage-verses-model');
const real=JSON.parse(fs.readFileSync(path.join(__dirname,'../../_content/homepage-verses.json'),'utf8'));
const directory=()=>({schemaVersion:1,verses:[{id:'fixture',reference:'Fixture',translation:'NLT',quotation:'Approved test text.',startDate:'2026-10-05',endDate:'2026-10-11',published:true,note:''}]});
const identity = { auth_typ: 'aad', claims: Object.entries({ tid: '9188040d-6c67-4c5b-b112-36a304b66dad', oid: '00000000-0000-0000-f978-44e4d44cc925', sub: 'AAAAAAAAAAAAAAAAAAAAACmKQtkQPpxJMB93l8aduYc', iss: 'https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0' }).map(([typ, val]) => ({ typ, val })) };
const SHA = 'a'.repeat(40), NEXT_SHA = 'c'.repeat(40), COMMIT = 'd'.repeat(40);
function request(method = 'PUT', homepageVerses = directory(), options = {}) {
  const principal = options.principal === undefined ? identity : options.principal;
  const headers = new Headers({ 'Content-Type': 'application/json', ...(options.headers || {}) });
  if (principal) headers.set('x-ms-client-principal', typeof principal === 'string' ? principal : Buffer.from(JSON.stringify(principal)).toString('base64'));
  const payload = options.body === undefined ? { sha: SHA, homepageVerses, ...options.extra } : options.body;
  const text = typeof payload === 'string' ? payload : JSON.stringify(payload);
  return { method, headers, query: new URLSearchParams(options.query || ''), body: new Blob([text]).stream() };
}

function fixture(options={}){const reads=[],writes=[],permissions=[];const handler=createHomepageVersesHandler({readConfiguration:()=>({}),createClient:async(_c,p)=>{permissions.push(p);return{rest:{repos:{getContent:async params=>{reads.push(params);return{data:{type:'file',path:params.path,sha:SHA,encoding:'base64',content:Buffer.from(JSON.stringify(options.current||directory())).toString('base64')}}},createOrUpdateFileContents:async params=>{writes.push(params);if(options.race)throw{status:409};return{data:{content:{sha:NEXT_SHA},commit:{sha:COMMIT}}}}}}}}});return{handler,reads,writes,permissions}}
test('Bible verses GET includes authenticated drafts and preserves every genuine current record',async()=>{const f=fixture({current:real});const r=await f.handler(request('GET'));assert.equal(r.status,200);assert.deepEqual(r.jsonBody.homepageVerses,real);assert.equal(r.jsonBody.sha,SHA);assert.deepEqual(f.reads,[{owner:'micklehamchurch',repo:'website',ref:'Dev',path:'_content/homepage-verses.json'}]);assert.equal(f.writes.length,0);assert.deepEqual(validateHomepageVerses(real),real)});
test('Bible verses gates missing/malformed/non-admin and browser-supplied identity before any repository access',async()=>{for(const principal of [null,'bad', {...identity,claims:identity.claims.map(c=>c.typ==='sub'?{...c,val:'wrong'}:c)}])for(const method of ['GET','PUT']){const f=fixture();const r=await f.handler(request(method,directory(),{principal,headers:{'x-ms-client-principal-id':'spoof','x-admin-email':'edward.popov@outlook.com'}}));assert.equal(r.status,principal&&principal!=='bad'?403:401);assert.equal(f.reads.length,0);assert.equal(f.writes.length,0)}});
test('Bible verses dedicated Dev publishing supports add/edit/draft/remove',async()=>{const d=directory();d.verses[0].quotation='Changed text';d.verses.push({...d.verses[0],id:'draft',published:false});const f=fixture();assert.equal((await f.handler(request('PUT',d))).status,200);const w=f.writes[0];assert.equal(w.owner,'micklehamchurch');assert.equal(w.repo,'website');assert.equal(w.branch,'Dev');assert.equal(w.path,'_content/homepage-verses.json');assert.equal(w.sha,SHA);assert.deepEqual(JSON.parse(Buffer.from(w.content,'base64')),d);const removed={schemaVersion:1,verses:[]};assert.equal((await fixture({current:d}).handler(request('PUT',removed))).status,200)});
test('Bible verses rejects browser target selectors, extra schema keys and altered section metadata',async()=>{for(const extra of [{branch:'main'},{path:'x'},{owner:'other'},{repository:'other'},{filename:'x'},{administrator:true}]){const f=fixture();assert.equal((await f.handler(request('PUT',directory(),{extra}))).status,400);assert.equal(f.writes.length,0)}const f=fixture();assert.equal((await f.handler(request('PUT',directory(),{query:'branch=main'}))).status,400);const d=directory();d.extra=true;assert.equal((await f.handler(request('PUT',d))).status,400)});
test('Bible verses stale SHA or GitHub race returns 409, no-op never requests write permission',async()=>{const f=fixture();assert.equal((await f.handler(request('PUT',directory(),{extra:{sha:'e'.repeat(40)}}))).status,409);assert.equal(f.writes.length,0);const d=directory();d.verses[0].quotation='Changed';assert.equal((await fixture({race:true}).handler(request('PUT',d))).status,409);const same=fixture();assert.equal((await same.handler(request('PUT'))).jsonBody.unchanged,true);assert.deepEqual(same.permissions,['read'])});
test('Bible verses validation blocks incomplete published wording and overlapping weeks before repository access',async()=>{for(const change of [{reference:''},{quotation:''},{translation:''},{quotation:'x'.repeat(321)},{quotation:'<script>'},{startDate:'2026-10-06'}]){const d=directory();Object.assign(d.verses[0],change);const f=fixture();assert.equal((await f.handler(request('PUT',d))).status,400);assert.equal(f.reads.length,0)}const d=directory();d.verses.push({...d.verses[0],id:'overlap'});assert.equal((await fixture().handler(request('PUT',d))).status,400)});
test('Bible verses rejects malformed or excessive bounded bodies without repository access',async()=>{for(const [options,status]of [[{body:'{'},400],[{body:'x'.repeat(MAX_BODY_BYTES+1)},413],[{headers:{'content-length':String(MAX_BODY_BYTES+1)}},413],[{headers:{'content-type':'text/plain'}},400]]){const f=fixture();assert.equal((await f.handler(request('PUT',directory(),options))).status,status);assert.equal(f.reads.length,0)}});
test('Azure HttpRequest body streams follow the same authorized Bible verses path',async()=>{const {HttpRequest}=require('@azure/functions');const d=directory();d.verses[0].quotation='Azure fixture';const r=request('PUT',d);const httpRequest=new HttpRequest({method:'PUT',url:'https://example.org/api/homepageVerses',headers:Object.fromEntries(r.headers),body:{string:JSON.stringify({sha:SHA,homepageVerses:d})}});const f=fixture();assert.equal((await f.handler(httpRequest)).status,200);assert.equal(f.writes.length,1)});
