const test=require('node:test'),assert=require('node:assert/strict');
const {status,pending,toggleLabel,changeCount,draftArchive}=require('../clergy-status');
const record=published=>({id:'fixture',displayName:'Test',published});
test('new staged record never claims published before authoritative persistence',()=>{assert.equal(status(record(true),undefined),'Draft');assert.equal(pending(record(true),undefined),'Ready to publish');assert.equal(status(record(false),undefined),'Draft');assert.equal(pending(record(false),undefined),'Draft not saved');assert.equal(toggleLabel(record(true),undefined),'Undo');});
test('persisted draft and pending publication remain distinguished',()=>{assert.equal(status(record(false),record(false)),'Draft');assert.equal(pending(record(false),record(false)),'');assert.equal(status(record(true),record(false)),'Draft');assert.equal(pending(record(true),record(false)),'Ready to publish');assert.equal(toggleLabel(record(true),record(false)),'Undo');});
test('published state comes only from authoritative snapshot; edits and unpublish stay pending',()=>{assert.equal(status(record(true),record(true)),'Published');assert.equal(pending(record(true),record(true)),'');assert.equal(status({...record(true),displayName:'Edited'},record(true)),'Published');assert.equal(pending({...record(true),displayName:'Edited'},record(true)),'Changes not published');assert.equal(status(record(false),record(true)),'Published');assert.equal(pending(record(false),record(true)),'Will be unpublished');assert.equal(toggleLabel(record(false),record(true)),'Keep published');});
test('failed publication leaves staged state unpublished until a successful committed response is adopted',()=>{const staged=record(true);let committed;assert.equal(status(staged,committed),'Draft');const failed={ok:false};if(failed.ok)committed=staged;assert.equal(status(staged,committed),'Draft');assert.equal(pending(staged,committed),'Ready to publish');const success={ok:true,archive:{records:[record(true)]}};if(success.ok)committed=success.archive.records[0];assert.equal(status(staged,committed),'Published');assert.equal(pending(staged,committed),'');});
test('pending summary counts changed people rather than individual fields',()=>{const committed={records:[record(true),{...record(false),id:'other'}]};assert.equal(changeCount(committed,committed),0);const working=structuredClone(committed);working.records[0].displayName='Edited';working.records[0].role='Rector';working.records.push({...record(false),id:'new'});assert.equal(changeCount(working,committed),2);});
test('saving drafts keeps published edits, unpublishing and ready profiles pending',()=>{const publicRecord=record(true),draft={...record(false),id:'draft'};const committed={records:[publicRecord,draft]};const working={records:[{...publicRecord,published:false,displayName:'Edited public'},{...draft,displayName:'Edited draft'},{...record(false),id:'new-draft'},{...record(true),id:'ready'}]};const saved=draftArchive(working,committed);assert.deepEqual(saved.records.find(r=>r.id===publicRecord.id),publicRecord);assert.equal(saved.records.find(r=>r.id==='draft').displayName,'Edited draft');assert.equal(saved.records.find(r=>r.id==='new-draft').published,false);assert(!saved.records.some(r=>r.id==='ready'));assert.equal(working.records[0].published,false);assert.equal(changeCount(working,saved),2);});
