const test=require('node:test'),assert=require('node:assert/strict');
const {status,pending,toggleLabel,changeCount,draftArchive}=require('../clergy-status');
const record=published=>({id:'fixture',displayName:'Test',published});
test('new staged record never claims published before authoritative persistence',()=>{assert.equal(status(record(true),undefined),'Draft');assert.equal(pending(record(true),undefined),'Ready to publish');assert.equal(status(record(false),undefined),'Draft');assert.equal(pending(record(false),undefined),'Draft not saved');assert.equal(toggleLabel(record(true),undefined),'Undo');});
test('persisted draft and pending publication remain distinguished',()=>{assert.equal(status(record(false),record(false)),'Draft');assert.equal(pending(record(false),record(false)),'');assert.equal(status(record(true),record(false)),'Draft');assert.equal(pending(record(true),record(false)),'Ready to publish');assert.equal(toggleLabel(record(true),record(false)),'Undo');});
test('published state comes only from authoritative snapshot; edits and unpublish stay pending',()=>{assert.equal(status(record(true),record(true)),'Published');assert.equal(pending(record(true),record(true)),'');assert.equal(status({...record(true),displayName:'Edited'},record(true)),'Published');assert.equal(pending({...record(true),displayName:'Edited'},record(true)),'Changes not published');assert.equal(status(record(false),record(true)),'Published');assert.equal(pending(record(false),record(true)),'Will be unpublished');assert.equal(toggleLabel(record(false),record(true)),'Keep published');});
test('failed publication leaves staged state unpublished until a successful committed response is adopted',()=>{const staged=record(true);let committed;assert.equal(status(staged,committed),'Draft');const failed={ok:false};if(failed.ok)committed=staged;assert.equal(status(staged,committed),'Draft');assert.equal(pending(staged,committed),'Ready to publish');const success={ok:true,archive:{records:[record(true)]}};if(success.ok)committed=success.archive.records[0];assert.equal(status(staged,committed),'Published');assert.equal(pending(staged,committed),'');});
test('pending summary counts changed people rather than individual fields',()=>{const committed={records:[record(true),{...record(false),id:'other'}]};assert.equal(changeCount(committed,committed),0);const working=structuredClone(committed);working.records[0].displayName='Edited';working.records[0].role='Rector';working.records.push({...record(false),id:'new'});assert.equal(changeCount(working,committed),2);});
test('saving drafts keeps published edits, unpublishing and ready profiles pending',()=>{const publicRecord=record(true),draft={...record(false),id:'draft'};const committed={records:[publicRecord,draft]};const working={records:[{...publicRecord,published:false,displayName:'Edited public'},{...draft,displayName:'Edited draft'},{...record(false),id:'new-draft'},{...record(true),id:'ready'}]};const saved=draftArchive(working,committed);assert.deepEqual(saved.records.find(r=>r.id===publicRecord.id),publicRecord);assert.equal(saved.records.find(r=>r.id==='draft').displayName,'Edited draft');assert.equal(saved.records.find(r=>r.id==='new-draft').published,false);assert(!saved.records.some(r=>r.id==='ready'));assert.equal(working.records[0].published,false);assert.equal(changeCount(working,saved),2);});
const {undoRecord}=require('../clergy-status');
test('Undo pending publication restores the saved Draft, photograph and zero pending count',()=>{const saved={...record(false),primaryImage:{src:'portrait.jpg',alt:'Saved photograph'},internalNotes:'Research'};const staged={...structuredClone(saved),published:true,internalNotes:'Temporary edit'};assert.equal(pending(staged,saved),'Ready to publish');assert.equal(changeCount({records:[staged]},{records:[saved]}),1);const undone=undoRecord(staged,saved);assert.deepEqual(undone,saved);assert.equal(status(undone,saved),'Draft');assert.equal(pending(undone,saved),'');assert.equal(changeCount({records:[undone]},{records:[saved]}),0);assert.notEqual(undone.primaryImage,saved.primaryImage);});
test('Undo pending unpublication restores authoritative Published state and photographs',()=>{const saved={...record(true),archiveImages:[{src:'archive.jpg'}]};const staged={...structuredClone(saved),published:false};assert.equal(status(staged,saved),'Published');assert.equal(pending(staged,saved),'Will be unpublished');const undone=undoRecord(staged,saved);assert.deepEqual(undone,saved);assert.equal(status(undone,saved),'Published');assert.equal(pending(undone,saved),'');});
test('Undo one person decreases multiple pending count without clearing another person',()=>{const saved=[record(false),{...record(true),id:'other'}];const staged=saved.map(r=>({...r,published:!r.published}));assert.equal(changeCount({records:staged},{records:saved}),2);staged[0]=undoRecord(staged[0],saved[0]);assert.equal(changeCount({records:staged},{records:saved}),1);assert.equal(pending(staged[1],saved[1]),'Will be unpublished');staged[1]=undoRecord(staged[1],saved[1]);assert.equal(changeCount({records:staged},{records:saved}),0);});
test('Undo never mutates authoritative state and a subsequent refresh stays clean',()=>{const saved=record(false),staged={...saved,published:true};const undone=undoRecord(staged,saved);assert.equal(staged.published,true);assert.equal(saved.published,false);const refreshed=structuredClone(saved);assert.deepEqual(undone,refreshed);assert.equal(pending(refreshed,saved),'');});
test('Undo an unsaved person cancels publication without deleting its fields or photograph',()=>{const staged={...record(true),primaryImage:{src:'upload:fixture'},biography:['History']};const undone=undoRecord(staged,undefined);assert.deepEqual(undone,{...staged,published:false});assert.equal(status(undone,undefined),'Draft');assert.equal(pending(undone,undefined),'Draft not saved');});

test('pending removals count once per person and Undo removes only that pending action',()=>{const committed={records:[record(true),{...record(false),id:'draft'}]},working=structuredClone(committed);assert.equal(changeCount(working,committed,['fixture']),1);working.records[0].displayName='Edited';assert.equal(changeCount(working,committed,['fixture','draft']),2);working.records[0]=undoRecord(working.records[0],committed.records[0]);assert.equal(changeCount(working,committed,['draft']),1);assert.equal(changeCount(working,committed,[]),0);assert.equal(status(working.records[0],committed.records[0]),'Published');});
test('Save drafts never persists pending removal and keeps the authoritative public snapshot',()=>{const committed={records:[record(true),{...record(false),id:'draft'}]},working=structuredClone(committed);const next=draftArchive(working,committed);assert.deepEqual(next,committed);assert.equal(changeCount(working,next,['fixture','draft']),2);});
